### ISSUE TITLE
module size is big

### ISSUE THREAD

**Issue by mcgradycchen** [gagern/libxmljs#6]
Hi all,

I installed the libxmljs using command 'npm install libxmljs-mt'.

Then I found the sizeof libxmljs-mt is very big, it's up to 32113020 bytes,

-rw-rw-r--.  1 32113020 Jan 12 10:48 libxmljs-mt.tar.gz

Would you like to provide some way the reduce the size of this package ?

Thanks~

**Comment by mcgradycchen** [comment]
Hi,

I manually intall the libxmljs with "npm install libxmljs",

The package size is 5522219, it is reasonable.
-rw-rw-r--. 1 o365-user o365-user  5522219 Jan 12 11:04 libxmljs.tar.gz

Thanks

**Comment by gagern** [comment]
What version of libxmljs are you using, and how are you getting that tarball? The current version of libxmljs-mt is 0.16.1. Its tarball has 5,095,981 bytes. libxmljs-mt@0.15.2 was considerably larger, because I accidentially packaged some windows build debugging data in there. I keep forgetting that npm even publishes files not committed to git. But even that file only had 29,396,297 bytes in the official repository. So I don't see where you go that tarball from.

**Comment by gagern** [comment]
I guess what you had was 0.15.2 with local build results added. I can't modify a version once it's been published, but other versions should be fine. Nevertheless, I just wrote ec3fc7fc72fdcf5c1aabca850916e62f6e9021b5 to reduce the file size even further, by excluding things from the libxml repo, like test cases and documentation.

**Comment by mcgradycchen** [comment]
Hi Gagern,

Thanks for your reply!

You said right. I have the libxmljs-mt@0.15.2 and local build install. 
I need to install the libxslt@0.6.1 (the latest version), it depends on libxmljs-mt@0.15.2. 

I saw the latest source code of libxslt is depends on libxmljs-mt@0.16.0. In the next release, this issue will be gone. 

Many Thanks~~
